//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace лаба_компиляторы_1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("лаба_компиляторы_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_circle_create_expand_new_plus_icon_123218 {
            get {
                object obj = ResourceManager.GetObject("add_circle_create_expand_new_plus_icon_123218", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_file_icon_icons_com_56095 {
            get {
                object obj = ResourceManager.GetObject("copy-file_icon-icons.com_56095", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_cut_icon_124981 {
            get {
                object obj = ResourceManager.GetObject("edit_cut_icon_124981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;User Guide&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot;&gt;
        ///    &lt;h2 align=&quot;center&quot;&gt;User Guide for the &quot;Compiler&quot; Application&lt;/h2&gt;
        ///    
        ///    &lt;h3 align=&quot;left&quot;&gt;Table of Contents&lt;/h3&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;&lt;a href=&quot;#functions&quot;&gt;Application Functions&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;#menu&quot;&gt;Description of Main Menu Items&lt;/a&gt;
        ///            &lt;ol&gt;
        ///                &lt;a href=&quot;#file&quot;&gt;&lt;li&gt;File&lt;/li&gt;&lt;/a&gt;
        ///                &lt;a href=&quot;#edit&quot;&gt;&lt;li&gt;Edit&lt;/li&gt;&lt;/a&gt;
        ///           [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_icon_173134 {
            get {
                object obj = ResourceManager.GetObject("folder_open_icon_173134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_icon_icons_com_55891 {
            get {
                object obj = ResourceManager.GetObject("Help_icon-icons.com_55891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_information_icon_178159 {
            get {
                object obj = ResourceManager.GetObject("info_information_icon_178159", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_120009_png {
            get {
                object obj = ResourceManager.GetObject("paste_120009.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo_arrow_1_icon_icons_com_56892 {
            get {
                object obj = ResourceManager.GetObject("redo-arrow-1_icon-icons.com_56892", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Руководство пользователя&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;white&quot; text=&quot;black&quot;&gt;
        ///    &lt;h2 align=&quot;center&quot;&gt;Руководство пользователя к приложению &quot;Компилятор&quot;&lt;/h2&gt;
        ///    
        ///    &lt;h3 align=&quot;left&quot;&gt;Содержание&lt;/h3&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;&lt;a href=&quot;#functions&quot;&gt;Функции приложения&lt;/a&gt;&lt;/li&gt;
        ///        &lt;li&gt;&lt;a href=&quot;#menu&quot;&gt;Описание основных пунктов меню&lt;/a&gt;
        ///            &lt;ol&gt;
        ///                &lt;a href=&quot;#file&quot;&gt;&lt;li&gt;Файл&lt;/li&gt;&lt;/a&gt;
        ///                &lt;a href=&quot;#edit&quot;&gt;&lt;li&gt;Правка&lt;/li&gt;&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_icon_125167 {
            get {
                object obj = ResourceManager.GetObject("save_icon_125167", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start_button_icon_icons_com_53873 {
            get {
                object obj = ResourceManager.GetObject("start-button_icon-icons.com_53873", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo_black_arrow_pointing_to_left_icon_icons_com_56880 {
            get {
                object obj = ResourceManager.GetObject("undo-black-arrow-pointing-to-left_icon-icons.com_56880", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
